#define RESET			0x00

#define NMI			0x1C
#define TRAP0			0x20
#define TRAP1			0x24
#define TRAP2			0x28
#define TRAP3			0x2C

#define IRQ_0			0x30
#define IRQ_1			0x34
#define IRQ_2			0x38
#define IRQ_3			0x3C
#define IRQ_4			0x40
#define IRQ_5			0x44
#define IRQ_6			0x48
#define IRQ_7			0x4C

#define WDT_WOVI		0x50
#define CMI			0x54

#define ITU_IMIA0		0x60
#define ITU_IMIB0		0x64
#define ITU_OVI0		0x68

#define ITU_IMIA1		0x70
#define ITU_IMIB1		0x74
#define ITU_OVI1		0x78

#define ITU_IMIA2		0x80
#define ITU_IMIB2		0x84
#define ITU_OVI2		0x88

#define ITU_IMIA3		0x90
#define ITU_IMIB3		0x94
#define ITU_OVI3		0x98

#define ITU_IMIA4		0xA0
#define ITU_IMIB4		0xA4
#define ITU_OVI4		0xA8

#define DMAC_DEND0A		0xB0
#define DMAC_DEND0B		0xB4
#define DMAC_DEND1A		0xB8
#define DMAC_DEND1B		0xBC

#define DMAC_DEND2A		0xC0
#define DMAC_DEND2B		0xC4
#define DMAC_DEND3A		0xC8
#define DMAC_DEND3B		0xCC

#define SCI_ERI0		0xD0
#define SCI_RXI0		0xD4
#define SCI_TXI0		0xD8
#define SCI_TEI0		0xDC

#define SCI_ERI1		0xE0
#define SCI_RXI1		0xE4
#define SCI_TXI1		0xE8
#define SCI_TEI1		0xEC

#define AD_ADI			0xF0

